import { z } from 'zod';
const text = z.string().trim().min(1, 'Este campo es obligatorio.');
const optionalText = z.string().trim().max(500).nullable();
const formDate = z.union([z.literal(''), z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Ingresa una fecha válida.')]);
const dateRange = <T extends z.ZodRawShape>(shape: T) => z.object(shape).strict().superRefine((value, context) => { const v = value as Record<string, unknown>; if (v.validFrom && v.validUntil && v.validFrom > v.validUntil) context.addIssue({ code: 'custom', path: ['validUntil'], message: 'La fecha de término debe ser igual o posterior a la fecha de inicio.' }); });
export const officeFormSchema = dateRange({ officeCode: text, name: text, officeType: z.enum(['HEADQUARTERS', 'BRANCH', 'OPERATING_OFFICE', 'TRAINING_SITE', 'OTHER']), street: text, city: text, commune: text, region: text, country: z.string().trim().length(2, 'Usa el código de país de dos letras.'), postalCode: z.string().max(500), email: z.union([z.literal(''), z.string().email('Ingresa un correo electrónico válido.')]), phone: z.string().max(500), validFrom: formDate, validUntil: formDate, notes: z.string().max(500) });
export const representativeFormSchema = dateRange({ firstName: text, lastName: text, taxId: text, email: z.union([z.literal(''), z.string().email('Ingresa un correo electrónico válido.')]), phone: z.string().max(500), roleTitle: text, validFrom: formDate, validUntil: formDate, appointmentDocumentId: z.union([z.literal(''), z.string().uuid('Ingresa un identificador de documento válido.')]), notes: z.string().max(500) });
export type OfficeFormValues = z.infer<typeof officeFormSchema>; export type RepresentativeFormValues = z.infer<typeof representativeFormSchema>;
const common = { id: z.string().uuid(), otecProfileId: z.string().uuid(), validFrom: z.string().nullable(), validUntil: z.string().nullable(), notes: optionalText, createdAt: z.string().datetime(), updatedAt: z.string().datetime(), version: z.number().int().positive() };
export const officeSchema = z.object({ ...common, officeCode: z.string(), name: z.string(), officeType: z.enum(['HEADQUARTERS', 'BRANCH', 'OPERATING_OFFICE', 'TRAINING_SITE', 'OTHER']), status: z.enum(['DRAFT', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED']), street: z.string(), city: z.string(), commune: z.string(), region: z.string(), country: z.string(), postalCode: optionalText, email: z.string().email().nullable(), phone: optionalText }).strict();
export const representativeSchema = z.object({ ...common, firstName: z.string(), lastName: z.string(), taxId: z.string(), email: z.string().email().nullable(), phone: optionalText, roleTitle: z.string(), active: z.boolean(), appointmentDocumentId: z.string().uuid().nullable() }).strict();
export type OtecOffice = z.infer<typeof officeSchema>; export type LegalRepresentative = z.infer<typeof representativeSchema>;
export const officePayloadSchema = z.object({ officeCode: text, name: text, officeType: z.enum(['HEADQUARTERS', 'BRANCH', 'OPERATING_OFFICE', 'TRAINING_SITE', 'OTHER']), street: text, city: text, commune: text, region: text, country: z.string().length(2), postalCode: optionalText.optional(), email: z.string().email().nullable().optional(), phone: optionalText.optional(), validFrom: z.string().nullable().optional(), validUntil: z.string().nullable().optional(), notes: optionalText.optional() }).strict();
export const representativePayloadSchema = z.object({ firstName: text, lastName: text, taxId: text, email: z.string().email().nullable().optional(), phone: optionalText.optional(), roleTitle: text, validFrom: z.string().nullable().optional(), validUntil: z.string().nullable().optional(), appointmentDocumentId: z.string().uuid().nullable().optional(), notes: optionalText.optional() }).strict();
export type OfficePayload = z.infer<typeof officePayloadSchema>; export type RepresentativePayload = z.infer<typeof representativePayloadSchema>;
export type AdministrativeFilters = { page: number; pageSize: number; status?: string; type?: string; validAt?: string; validFromAfter?: string; validUntilFrom?: string; validUntilBefore?: string }; export type Page<T> = { data: T[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const nullable = (v: string) => v.trim() || null; const date = (v: string) => v || null;
export function toOfficePayload(v: OfficeFormValues): OfficePayload { return { officeCode: v.officeCode.trim(), name: v.name.trim(), officeType: v.officeType, street: v.street.trim(), city: v.city.trim(), commune: v.commune.trim(), region: v.region.trim(), country: v.country.trim().toUpperCase(), postalCode: nullable(v.postalCode), email: nullable(v.email), phone: nullable(v.phone), validFrom: date(v.validFrom), validUntil: date(v.validUntil), notes: nullable(v.notes) }; }
export function toRepresentativePayload(v: RepresentativeFormValues): RepresentativePayload { return { firstName: v.firstName.trim(), lastName: v.lastName.trim(), taxId: v.taxId.trim(), email: nullable(v.email), phone: nullable(v.phone), roleTitle: v.roleTitle.trim(), validFrom: date(v.validFrom), validUntil: date(v.validUntil), appointmentDocumentId: nullable(v.appointmentDocumentId), notes: nullable(v.notes) }; }
